sudo: required
services: 
  - docker

before_install:
  - docker build -t harrysl21/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harrysl21/docker-react npm run test -- --coverage
